### ISSUE TITLE
The issue file attachment is ignored

### ISSUE THREAD

**Issue by ujos** [piceaTech/node-gitlab-2-github#106]
I'm migrating issues from GitLab to GitHub and noticed that file attachments like binaries or source code attached to comment/description are ignored. 

For example original issue on GitLab contains following text:

```txt
[attached](/uploads/d31d82da5d7a0753a418f845f30f1968/libSomeLib.dll)
```

The issue created by node-gitlab-2-github contains following text:

```txt
[attached](/uploads/d31d82da5d7a0753a418f845f30f1968/libSomeLib.dll)
```

Images somehow works... well, I did not provide keys for S3. At least I see an error that image cannot be uploaded. The file attachments are just ignored.

**Comment by ujos** [comment]
Looks like it is because of following regex:

```ts
const regexp = /!\[([^\]]+)\]\((\/uploads[^)]+)\)/g;
```

Here expected that link tag starts with exclamation mark.

**Comment by ujos** [comment]
I've removed the `!` char and now I get error 503.

```ts
 res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 503,
      statusMessage: 'Service Temporarily Unavailable',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://gitlab.com/users/sign_in',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    }
```

**Comment by mdbenito** [comment]
No, it is not possible, see [this discussion](https://gitlab.com/gitlab-org/gitlab/-/issues/24155). One can use a browser session cookie instead, as in #117
