### ISSUE TITLE
If settings.debug is true, no issues are transferred

### ISSUE THREAD

**Issue by markuslf** [piceaTech/node-gitlab-2-github#133]
Problem is located in `githubHelper.ts`, function `importIssueAndComments()`, line 451:

[`if (settings.debug) return Promise.resolve({ data: issue });`](https://github.com/piceaTech/node-gitlab-2-github/blob/cc3059364c6d208d97b260d2ec8b37b40fd1d059/src/githubHelper.ts#L451)

If `settings.debug` is `true`, issue importing simply states `...DONE migrating issue #4711`, and actually does nothing at all.

**Comment by spruce** [comment]
Works as intended: https://github.com/piceaTech/node-gitlab-2-github#debug
