### ISSUE TITLE
Ran into issues while migrating data to an organization's repository

### ISSUE THREAD

**Issue by boyvanduuren** [piceaTech/node-gitlab-2-github#14]
I tried using this tool to migrate issues from gitlab to an organization's github repository. However, that didn't quite work out at first, because the repository's URL was encoded to `https://.../repos/username/organizationname%2Freponame`.
However, after changing my username to the organization's name in `settings.json` everything worked as expected (saving us quite some work, thanks! :))

**Comment by spruce** [comment]
With #15 it should work, no?

**Comment by spruce** [comment]
Closing as of inactivity
