### ISSUE TITLE
Exit and documentation_url not found

### ISSUE THREAD

**Issue by T3KN0KRAT** [piceaTech/node-gitlab-2-github#18]
The error message is:

```
{ gitlab:
   { url: 'http://gitlab.com/',
     token: 'XXXX',
     projectID: 2394773 },
  github:
   { url: 'api.github.com',
     pathPrefix: '',
     owner: 'GIN-Network',
     username: 'T3KN0KRAT',
     password: 'XXXXX',
     repo: 'gitlabcontrol-test' },
  usermap: { 'adi': 'T3KN0KRAT' },
  projectmap: { 'GIN/gitlabcontrol-test': 'GIN-Network/gitlabcontrol-test' } }
Amount of gitlab milestones 0
{ [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
  code: 404 }
FAIL!
/Users/adi/w/py/GIN/tools/node-gitlab-2-github/index.js:216
        exit(1);
        ^

ReferenceError: exit is not defined
    at /Users/adi/w/py/GIN/tools/node-gitlab-2-github/index.js:216:9
    at module.exports.sendError (/Users/adi/w/py/GIN/tools/node-gitlab-2-github/node_modules/github/api/v3.0.0/index.js:32:13)
    at /Users/adi/w/py/GIN/tools/node-gitlab-2-github/node_modules/github/api/v3.0.0/issues.js:1020:29
    at callCallback (/Users/adi/w/py/GIN/tools/node-gitlab-2-github/node_modules/github/index.js:743:17)
    at IncomingMessage.<anonymous> (/Users/adi/w/py/GIN/tools/node-gitlab-2-github/node_modules/github/index.js:793:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Forgetting about the `exit is not defined` error, I don't see anywhere in the code that references a documentation_url. Might you have any ideas of what might be causing this?

**Comment by spruce** [comment]
Thanks for catching that error. gonna fix it.
That's right. As you can see in the stacktrace. The error actually comes from the guthub module
```
(/Users/adi/w/py/GIN/tools/node-gitlab-2-github/node_modules/github/api/v3.0.0/index.js:32:13 )
```
I have to look more into the second part.

**Comment by T3KN0KRAT** [comment]
Thanks a brazillion! If you do happen across a fix/workaround, could you please let me know? Even if it's just a diff; I'm working on a project right now that sure could use this. I'd really appreciate it.

Btw, awesome tool! I haven't found another like this.

**Comment by T3KN0KRAT** [comment]
Update: After thinking some more about this, the 404 clued me in that the destination repo on GitHub didn't exist; I was originally testing this to _create_ a new repo for me on GitHub, but this tool doesn't *DO* that, does it?

So, when I modified my settings file to point to an already-existing repo on GitHub, it seems to have worked.  The tool ended with:

```
Finished creating all issues and Comments




null undefined
``` 
But all of my issues are there. So I'm going to close this issue, but I suppose that you can re-open it if you want to keep track of that `exit is not defined` error.

Thanks for the speedy response!
