### ISSUE TITLE
Broken link when issue comment has an image

### ISSUE THREAD

**Issue by T3KN0KRAT** [piceaTech/node-gitlab-2-github#19]
GitLab hosts the images in comments "locally" (in my example: /uploads/1457ceabe9cd476cc28fb2d26c236bc4/Screen_Shot_2017-02-04_at_9.27.06_PM.png).

Whereas GitHub now hosts them on another domain (https://cloud.githubusercontent.com/assets/.)

However, node-gitlab-2-github, somewhere, uploaded that same image to https://github.com/uploads/1457ceabe9cd476cc28fb2d26c236bc4/Screen_Shot_2017-02-04_at_9.27.06_PM.png, which obviously results in a broken link:

![screen shot 2017-02-05 at 9 35 15 pm](https://cloud.githubusercontent.com/assets/1304734/22635846/8f6fba54-ebeb-11e6-9363-df76f9b46c7e.png)

**Comment by T3KN0KRAT** [comment]
Oh, this is in the github api module (routes.json) so it's not really something this tool messes with.  Please feel free to close this. I'm going to leave it open in case you want to track this.

**Comment by spruce** [comment]
If you have created a Issue over at the other repo I'd like to close this issue as I like clean repos.

**Comment by T3KN0KRAT** [comment]
I haven't created an issue over there, as I've found a work-around.  No reason to keep this one open.

**Comment by spruce** [comment]
Can you maybe document your workaround somewhere. I actually would like to have it in the README aswell for others who have the same problem

**Comment by jordanflagco** [comment]
I'm having this issue too, the Gitlab attachments are linking to `https://github.com/uploads/{{GitlabHash}}` instead of either being reuploaded to Github, or remaining linked to Gitlab.

**Comment by spruce** [comment]
I think we are currently not migrating any attachments. this commit did add labels to the issues which need attachments migrated manually: https://github.com/piceaTech/node-gitlab-2-github/commit/3fd53c8bdd9cf5952635ac6e28cfe8598c328b3c#diff-168726dbe96b3ce427e7fedce31bb0bcR312

**Comment by jordanflagco** [comment]
Yeah, I saw that it adds a label, which is helpful. I think I'll take a look at how difficult it would be to add automatic migrations while my team does the manual one. :smile:

**Comment by chraibi** [comment]
@spruce I don't about labeling the issue with "attachment" is nice. 

For my needs, I removed that part and fixed the link to the uploaded files as follows: 

in `function addMigrationLine(str, item)`

```
    if (str.indexOf('/uploads/') > -1)                                                                                                                                      
    {                                                                                                                                                                       
        str = str.slice(0,str.indexOf('/uploads/')) +  settings.gitlab.url + "/" + settings.github.owner + "/" + settings.github.repo  +                                    
str.slice(str.indexOf('/uploads/'))                                                                                                                                         
    }  
```

**Comment by spruce** [comment]
Ok, But doesn't mean that you need to push all your uploads into you repo? In my understanding the URL gets reformatted to :`github.com/owner/repo/uploads/*`, no?

**Comment by chraibi** [comment]
Actually, not. No need to push the uploaded file to GitHub.

For example this issue was merged to GitHub using your code:
 
https://github.com/JuPedSim/jpsfire/issues/10
with an uploaded file
https://gitlab.version.fz-juelich.de/JuPedSim/jpsfire/uploads/b7094e16b155fd19c9c16146c5799b82/test.txt

Not that the text `in GitLab` is a link to the original GitrLab-issue. (just in case something goes south we can still see the original version).

**Comment by spruce** [comment]
But this would mean there now exists a dependency of the new repo onto the old repo. Which I find kind of bad as this destroys the possibilty to move away and shut down your own instance / or beeing locked out later (leaving uni or something similar)

**Comment by chraibi** [comment]
You make a good point. The perfect solution would be to *automatically* upload the files to GitHub with some API-commands.  Any idea how to to it?

However, I think this issue was about fixing broken links, right?
