### ISSUE TITLE
concat problem

### ISSUE THREAD

**Issue by ohernan** [piceaTech/node-gitlab-2-github#2]
Hi,
I have a problem when run the index,js
TypeError: Cannot read property 'concat' of undefined

**Comment by spruce** [comment]
Do you mean in this line?
https://github.com/piceaTech/node-gitlab-2-github/blob/master/index.js#L146
might be because there was an error. gonna add rudimentary error handling

**Comment by spruce** [comment]
can you try https://github.com/piceaTech/node-gitlab-2-github/releases/tag/v0.1.3 ?

**Comment by ohernan** [comment]
Hi,
Thanks a lot, It's working now, However, I had to change the line
gitlab.projects.milestones.list
for
gitlab.projects.milestones.all
