### ISSUE TITLE
Can you provide any minimum GitLab version requirements?

### ISSUE THREAD

**Issue by affrae** [piceaTech/node-gitlab-2-github#21]
Do you have any information on the minimum version of GitLab required for this tool?

💜 
@affrae 👾

**Comment by spruce** [comment]
Not quite sure about it. But I would say around 7.10 maybe (??!?). Why do you ask? Do you have a version which is that old?

**Comment by affrae** [comment]
@spruce I wanted to get a customer to check it out as an example of using our APIs for migration from other VCSes. We were told they had an old version, but since then it turns out that they are using a version less than a year old, so Thi is not an issue any more...

Thanks!

💜 
@affrae 👾

**Comment by spruce** [comment]
Am I in some kind of special GitHub list of cool tools? 😜😳
