### ISSUE TITLE
TypeError: milestoneDataClosed.concat(...).map is not a function

### ISSUE THREAD

**Issue by Pmagnard** [piceaTech/node-gitlab-2-github#22]
Hello, 
at my first attempt to use this tool, I got the error:

> Amount of gitlab milestones 0
> C:\Users\PASCALMagnard\git\migration\issues\node-gitlab-2-github\index.js:228
>       milestoneData = milestoneDataClosed.concat(milestoneDataOpen).map(function(item) {
>                                                                     ^
> 
> TypeError: milestoneDataClosed.concat(...).map is not a function
>     at C:\Users\PASCALMagnard\git\migration\issues\node-gitlab-2-github\index.js:228:69
>     at C:\Users\PASCALMagnard\git\migration\issues\node-gitlab-2-github\node_modules\github\api\v3.0.0\issues.js:1047:17
>     at callCallback (C:\Users\PASCALMagnard\git\migration\issues\node-gitlab-2-github\node_modules\github\index.js:743:17)
>     at IncomingMessage.<anonymous> (C:\Users\PASCALMagnard\git\migration\issues\node-gitlab-2-github\node_modules\github\index.js:796:25)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by spruce** [comment]
hm. That looks kind of strange. Could you add a line like this before so we see what is happening:
```
console.log(milestoneDataClosed, milestoneDataOpen);
```
and report back what is happening.

**Comment by Pmagnard** [comment]
I solved my problem.  github.url and github.pathPrefix were improperly set in settings.json. Because of that, index.js was getting HTML fragments wrapping HTTP 302 messages (redirect) instead of the issues tracker data.

**Comment by spruce** [comment]
okay. Where could a error message being added?
