### ISSUE TITLE
Does this migrate a Wiki?

### ISSUE THREAD

**Issue by moubry** [piceaTech/node-gitlab-2-github#27]
I noticed in the description for this package, it alludes to migrating a Wiki from GitLab → GitHub. However, when you search the code of the project for the word "wiki", it isn't found anywhere.

Will this package migrate a Wiki?

**Comment by spruce** [comment]
I think wikis are in both worlds just a git repo of their own. So it will just be like a normal repo where you pull from the old and push to the new, no?

**Comment by moubry** [comment]
Yes and no.

Yes, you you simply `git clone` the GitLab wiki, and then turn around and `git push` to the GitHub remote. Then you’d have your entire GitLab wiki on GitHub.

However, critically, GitLab supports inline image uploads — you simply drag an image into the Markdown composition window, and it gets uploaded to a special GitLab image hosting service. GitHub doesn't have this functionality.

In order to migrate a GitLab wiki → GitHub with perfectly fidelity, you'd need to also handle bringing over images. Either by committing them to the wiki repo, or by committing them to the main project repository somewhere.

**Comment by spruce** [comment]
Yes, you're right. 

I haven't used the Gitlab wiki that much. I should probably remove the mention of the wiki in the description. If you want to create a PR it would much appreciated.

**Comment by aspearman** [comment]
@spruce The description of the repo still mentions migrating wikis

**Comment by Tibalt** [comment]
the descritpion should be updated. I worked for an hour to migrate the wiki but at last the images are not transferred corretly.

**Comment by spruce** [comment]
Done. Sorry for the delay.
