### ISSUE TITLE
This works well ❤️ thank you, just note that milestone with no due date gives error

### ISSUE THREAD

**Issue by simkimsia** [piceaTech/node-gitlab-2-github#29]
Hi there, your app works very well. Sending you ❤️ 

Just to let you know when the milestones in gitlab has no due date, there's an error with importing into github.

I think maybe because your default value for dates is not acceptable to github.

Once again, thank u for this app

**Comment by spruce** [comment]
Thanks for letting me know. It should be fixed now.
