### ISSUE TITLE
Import fail if the github project already have milestones

### ISSUE THREAD

**Issue by Bigorneau** [piceaTech/node-gitlab-2-github#3]
Hello,

When importing my project from gitlab to github I had to do it in two part because the github API shut me down with some kind of abuse mechanism

Here is the message I got

> [Error: {"message":"You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.","documentation_
url":"https://developer.github.com/v3#abuse-rate-limits"}]

Anyway when I tried later to import the rest of my issue (some were already imported to github) I got an error here [index.js#L70](../blob/229ac53af52100b779e43e2ac34eb75f7af77123/index.js#L70)

When debuging a little it appears that `getAllGHMilestones()` return a map an thus the test `if (milestoneDataMapped.indexOf(item.title) < 0)` always fail.

Here is the data that produced the issue:

```javascript
var milestoneDataMapped = [ { id: 2,
        iid: 1,
        project_id: 26,
        title: '24h',
        description: 'Milestone reached after everyone has spent 24h on development',
        state: 'active',
        created_at: '2015-06-16T12:26:25.000Z',
        updated_at: '2015-06-16T12:26:25.000Z',
        due_date: null } ];


var data = { id: 2,
        iid: 1,
        project_id: 26,
        title: '24h',
        description: 'Milestone reached after everyone has spent 24h on development',
        state: 'active',
        created_at: '2015-06-16T12:26:25.000Z',
        updated_at: '2015-06-16T12:26:25.000Z',
        due_date: null };
```

I tried the following diff and I was able to finish the import.

```diff
diff --git a/index.js b/index.js
index 7749ec6..ac4fc3f 100644
--- a/index.js
+++ b/index.js
@@ -59,7 +59,7 @@ if (settings.gitlab.projectID === null) {
       console.log(milestoneDataMapped);
       console.log('\n\n\n\n\n\n\n');

-      async.each(data, function(item, cb) {
+      async.each(data.title, function(item, cb) {
         if (milestoneDataMapped.indexOf(item.title) < 0) {
           console.log('Creating new Milestone', item.title);
           createMilestone(item, function(err, createMilestoneData) {
```

**Comment by spruce** [comment]
If you say it worked for you I'm not gonna check it and just merge. Thanks for finding this out. :+1:

**Comment by andres-duebi** [comment]
@spruce, please see PR #5. I believe the current code never creates milestones and I fixed the actual issue which was `err` being undefined in index.js#L70
