### ISSUE TITLE
Unable to connect to Github

### ISSUE THREAD

**Issue by prastut** [piceaTech/node-gitlab-2-github#31]
In setting.js I have the following setting for github: 

``` 
github: {
    owner: "https://api.github.com",
    username: "prastut",
    token: <token generated from Github>
    repo: "trenity"
  },
```
It throws up error not found. I think I am not able to authenticate from Github. Any help would be highly appreciated, thank you for making this project.

**Comment by spruce** [comment]
Hi,
the owner should not be the url to github. If you want to transfer something to your private account you just repeat your username as owner.

**Comment by spruce** [comment]
Closing as it is inactive.
