### ISSUE TITLE
Username mapping fix

### ISSUE THREAD

**Issue by SimonBiggs** [piceaTech/node-gitlab-2-github#37]
Here is my fix for username not mapping appropriately in the body of issues:

https://github.com/SimonBiggs/node-gitlab-2-github/commit/9aab9ca9e7298acc2e950de745d6207e79091c3c

Unfortunately my GitHub account is currently rate limited (from using this tool), so I can't submit a pull request with this patch.

**Comment by spruce** [comment]
Can be closed with #38 being accepted?

**Comment by SimonBiggs** [comment]
Should be.
