### ISSUE TITLE
What should be the projectmap

### ISSUE THREAD

**Issue by vivekgs2007** [piceaTech/node-gitlab-2-github#41]
I am getting the error: " Select which project ID should be transported to github. Edit the settings.js accordingly. (gitlab.projectID) "

My gitlab Project deatils:

19       orgStats       --       null

What I need to add in projectmap

My settings.js
"projectmap": {
    "orgStats": "test",
    //"gitlabgroup/projectname.2": "GitHubOrg/projectname.2"
  }

**Comment by spruce** [comment]
You have to edit the `settings.js` and enter into the field `gitlab.projectId` a project id which should be printed right before the message you wrote.
