### ISSUE TITLE
Needs dependencies updated

### ISSUE THREAD

**Issue by evanplaice** [piceaTech/node-gitlab-2-github#53]
NPM audit turns up w/ 2 security vulnerabilities and the issues transfer fails with an 'uncaught promise' error on Node 12+.

After updating the dependencies (ITT the gitlab dep was the issue) both of these issues were fixed.

**Comment by spruce** [comment]
Thanks for noting that. With 826bc4f93703e404498dc982b216b11235a51baa it should now be fixed.
