### ISSUE TITLE
Duplicate github Issues are created from gitlab merge requests

### ISSUE THREAD

**Issue by ashleyvega** [piceaTech/node-gitlab-2-github#65]
When a github PR cannot be created from a gitlab MR, for example because the source branch does not exist, a github Issue is created instead, with a title of `pullRequest.title.trim() + ' - [' + pullRequest.state + ']'`.

These github Issues are not searched when re-running the migration, resulting in duplicate github Issues being created from gitlab MRs.

**Comment by ashleyvega** [comment]
Looks like #62 might be describing the same problem, but it's hard to tell.

**Comment by spruce** [comment]
I think it should be the same.
