### ISSUE TITLE
Setting issue creator

### ISSUE THREAD

**Issue by ererkka** [piceaTech/node-gitlab-2-github#82]
Hi and thanks for this project for starters! We are migrating from a self-hosted GitLab instance to the open and `node-gitlab-2-github` seems to do the job nicely for issues etc.

Maybe a dummy question: All issues are created by the user running the migration process (me), and there is a piece of text in the comments telling the original author. Is there any way to create the issues with the names of the original users (with mappings), or is this a limitation of the GitHub API?

**Comment by spruce** [comment]
hi @ererkka,
Sorry for the long answer time.

As far as I know it is a limitation of the API. I think it is for security reasons. Elsewise I could write a comment in your name in a repo I'm just creating, right?

If I misunderstood you, feel free to reopen
