### ISSUE TITLE
Ability to specify to transfer labels, milestones, issues, or merge requests.

### ISSUE THREAD

**Issue by kdjstudios** [piceaTech/node-gitlab-2-github#85]
Currently this only allows for everything to be transferred. By adding the ability in the settings to specify which sections of content to transfer the user can choose only what needs to be transferred. 

NOTE: This could also help users who are running the application more then once to not have to re-transfer content that does not need to be updated.

**Comment by kdjstudios** [comment]
I believe I have added this ability. Created pull request #86. Please review and confirm. Thanks.

**Comment by mdbenito** [comment]
I think was indeed addressed and can be closed @spruce

**Comment by spruce** [comment]
@mdbenito indeed
