### ISSUE TITLE
Constant Error: GitHub RequestError [HttpError]: Bad credentials

### ISSUE THREAD

**Issue by MeerMusik** [piceaTech/node-gitlab-2-github#97]
Hello.

Thanks for this Project. After changing the "git@" URLs into "https" URLs, I was finally able to connect to GitLab. The Readme is outdated in a couple of Areas. Anyway, while I am trying to connect to GitHub, it constantly ends with the following Error Message:

`Could not access GitHub repo
RequestError [HttpError]: Bad credentials
    at C:\Dev\node-gitlab-2-github\node_modules\@octokit\request\dist-src\fetch-wrapper.js:49:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 401,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '80',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 03 Jul 2021 23:00:59 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0C53:6DB4:765AE6D:78864E4:60E0EC2B',
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '49',
    'x-ratelimit-reset': '1625353637',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '11',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/%7B%7BMeerMusik%7D%7D/%7B%7BAKKomPolTool%7D%7D',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.0 octokit-core.js/3.1.0 Node.js/16.4.0 (Windows 10; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest'
}
`

Type of Access Tokens tried:
* repo
* repo and gist
* repo and user

Any hint is welcome.
Thank you!

**Comment by MeerMusik** [comment]
Just tried it again and still get the same 401 Error. If someone, who knows GitHub's weird System well enough, could give me a hint, it would be much appreciated. Otherwise it seems that I need to manually copy + paste every Milestone and Label.

Thanks in advance!

**Comment by MeerMusik** [comment]
Trying to clone a Repo with Password and PAT fails with 'git clone'. The 'SmartGit' Tool does not fail entering the Token in the Passwork Input Field. Not sure why it does not fail - maybe auto detection of connection type.

**Comment by milljm** [comment]
I ran into the same issue. I foolishly included the "{{ and }}" characters in the settings.ts file. Basically:

```pre
  github: {
    // baseUrl: 'https://gitlab.mycompany.com:123/etc',
    owner: '{{repository owner (user or organization)}}',
    token: '{{token}}',
    repo: '{{repo}}',
  },
```
should be:
```pre
  github: {
    // baseUrl: 'https://gitlab.mycompany.com:123/etc',
    owner: 'my_cool_repo',
    token: 'ghp_abc1234567890',
    repo: 'target_repo',
  },
```

The same goes for your GitLab settings :)

**Comment by MeerMusik** [comment]
Interesting. My GitLab Token works with '{{}}', that is why I never thought to remove them. I blame my NodeJS Noob Level.

Well too late for me but hopefully it will help other people. Thanks anyway :)
